version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    environment:
      PHP_IDE_CONFIG: "serverName=wordy.loc"

  nginx:
    image: nginx:1.17.0-alpine
    volumes:
      - ./docker/nginx/wordy.conf:/etc/nginx/conf.d/wordy.conf:ro
      - .:/app
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=wordy.loc
      - NGINX_PORT=80
    command: sh -c "exec nginx -g 'daemon off;'"
    depends_on:
      - php